### ISSUE TITLE
Deno KV: c.session.value not unpacked

### ISSUE THREAD

**Issue by Rhal95** [shinosaki/hono-kv-session#5]
Hi 👋 

Deno KV will always return a `Deno.KvEntry` when using `kv.get()`. Even when no value is found for the key. If no value is found, the value in the entry is `null`. The `SessionManager` does not unpack this value and puts the `Deno.KvEntry` into `c.session.value`.
This means I have to unpack the value myself every time I want to access it. 
This also means I can not use the renew and regenerate functions. Those will just put the session value back into the `createSession` function which will nest the `Deno.KvEntry` in another `Deno.KvEntry`.

If you want I can submit a PR for this tomorrow.

**Comment by Rhal95** [comment]
Hi again 👋 
I fixed the unpacking of the KvEntry for Deno KV. Please take a look at the PR and tell me if everything is okay.
Thank you.

**Comment by shinosaki** [comment]
Thank you for pull request! Merged it.👍
Sorry for the delay🙇🙇

**Comment by shinosaki** [comment]
DenoKV の [`get()`](https://deno.land/api@v1.38.5?s=Deno.Kv&unstable=&p=prototype.get) は、値をそのまま返さず [`KvEntryMaybe`](https://deno.land/api@v1.38.5?s=Deno.KvEntryMaybe&unstable=) を返す仕様でした。
```js
{
  key: KvKey,
  value: null,
  versionstamp: null
}
```

このプルリクで `c.session.value` に `value` を代入するよう修正されました。
